### ISSUE TITLE
problems with ofxHTTP addon in XCode

### ISSUE THREAD

**Issue by carloscastellanos** [runwayml/ofxRunway#13]
It seems that ofxRunway.h cannot find ofxHTTP.h, but it has no problem finding it in ofxRunway.cpp.

<img width="762" alt="Screen Shot 2020-04-25 at 8 54 05 PM" src="https://user-images.githubusercontent.com/6315240/80294559-0d57d600-8738-11ea-95a4-ffd45acf2649.png">

Also ofxRunway.cpp is having some issues with ofxHTTP as well. Certin methods, don't exist, etc.

<img width="1123" alt="Screen Shot 2020-04-25 at 8 53 42 PM" src="https://user-images.githubusercontent.com/6315240/80294546-ee594400-8737-11ea-942d-23f1563a3e00.png">

I am in XCode 10.3, macOS 10.14.6, openFrameworks 0.10.1

**Comment by roymacdonald** [comment]
Hi, did you update ofxHTTP to its newest version?
Also, try updating the project using the project generator. Simply open ProjectGenerator, and drag and drop over it the folder of the project you want to use, then click update or generate and try compiling again.

**Comment by carloscastellanos** [comment]
Hi Roy,

I had cloned ofxHTTP from the master branch. I tried the stable branch and while that fixed the issue with ofxRunway.cpp, ofxRunway.h still could not find ofxHTTP.h. So I cloned the stable branch of openFrameworks itself and that fixed the issue. All of this is as recommended by the  ofxHTTP Github page but I hope my other addons are ok with running the openFrameworks stable branch.

Thanks

**Comment by roymacdonald** [comment]
mmm that's odd cause I use the OF master branch with no problem. 
Did you try updating the project? Those kind of problems are usually fixed by that. Also, you can try cleaning the project from the product menu in xcode, and then again but pressing the alt key which will now show clean build folder.
This kinda things are usually related to some dumbness of xcode rather than the addon.
let me know if you make any improvements or find out something else.

**Comment by carloscastellanos** [comment]
Yes, I updated the project and the issue persists.

Edit: I created a new 0.10.1 project with the ofxHTTP from the stable branch and the issue is gone now. I also created a new project with ofx 0.11.0 and that also has no issues

**Comment by roymacdonald** [comment]
Hi, so what was the problem then? were you able to nail it? I've just tested it on xcode 11.2.1, macos 10.14.6 using the newest nightly build (of_v20200427_osx_release) and of_v0.11.0_osx_release and it works properly on both. I did fresh installs of each.

**Comment by carloscastellanos** [comment]
I think the problem is probably XCode weirdness as you said (but I am not sure), which can avoided by simply cloning the stable rather than the master branch of ofxHTTP (as they suggest). Cleaning or updating projects that use the the master branch have no effect. I'll download XCode 11 and try it there as well.

**Comment by roymacdonald** [comment]
Sure. It worked for me with the master branch of ofxHTTP although.
Most of the times that I've seen this behavior has been some sort of Xcode weirdness.
I'll close this issue.
Best.
